"""
Internship AI Microservice — FastAPI application entry point.

Design rule #1: Pure similarity service — no mandatory filtering or business logic
lives here; hard filters (country, work_mode, duration, stipend, etc.) run in
Spring Boot before semantic matching.

Design rule #2: Cosine similarity is a ranking signal only, never framed as a
percentage match or probability.

Design rule #5: This service is called over HTTP by Spring Boot.
No extraction or ML logic lives inside the Spring Boot process.

Endpoints:
  GET  /health          — liveness probe
  POST /extract-resume  — accept a PDF, return structured profile sections
  POST /embed           — accept text, return 384-dim SBERT embedding vector
  POST /match           — accept resume and internships, return cosine similarity scores
                          sorted descending by similarity_score
"""
from __future__ import annotations

from contextlib import asynccontextmanager
from typing import Any, Optional, Union

from fastapi import FastAPI, File, HTTPException, UploadFile
from pydantic import BaseModel, Field

from app.extractor import extract_text_from_pdf, parse_sections
from app.matcher import compute_embedding, compute_matches, get_model


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Eagerly load the Sentence-BERT model on startup."""
    get_model()
    yield


app = FastAPI(
    title="Internship AI Service",
    description=(
        "Pure similarity & resume extraction microservice for the internship platform. "
        "Compliant with design rules #1 (pure similarity, no hard filters here) and #2 "
        "(raw cosine similarity scores only, no percentage or probability framing)."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Content-types that browsers / HTTP clients may send for PDF uploads.
# application/octet-stream is a common fallback when the client does not
# inspect the file before uploading.
_ACCEPTED_PDF_TYPES = {"application/pdf", "application/octet-stream"}


# ---------------------------------------------------------------------------
# Request / Response Schemas
# ---------------------------------------------------------------------------

class EmbedRequest(BaseModel):
    text: str = Field(
        ...,
        min_length=1,
        description="Text to encode into an SBERT dense vector",
        example="Backend software engineer with Java, Spring Boot, and MySQL experience.",
    )


class EmbedResponse(BaseModel):
    embedding: list[float] = Field(
        ...,
        description="384-dimensional dense SBERT vector generated by all-MiniLM-L6-v2",
    )
    dimensions: int = Field(
        384,
        description="Dimensionality of the embedding vector",
    )


class InternshipItem(BaseModel):
    id: Union[int, str] = Field(
        ...,
        description="Unique identifier for the internship (from database or external source)",
    )
    description: str = Field(
        ...,
        min_length=1,
        description="Internship job description or requirement text to match against",
    )
    title: Optional[str] = Field(
        None,
        description="Optional title of the internship role",
    )


class MatchRequest(BaseModel):
    resume: Union[str, dict[str, Any]] = Field(
        ...,
        description=(
            "Resume representation: either a plain text string or a structured dictionary "
            "of sections (e.g. skills, education, experience, projects)."
        ),
    )
    internships: list[InternshipItem] = Field(
        ...,
        description="List of internship postings to score against the resume",
    )


class MatchResultItem(BaseModel):
    id: Union[int, str] = Field(
        ...,
        description="Unique identifier of the matched internship",
    )
    similarity_score: float = Field(
        ...,
        description=(
            "Raw cosine similarity score between [-1.0, 1.0]. "
            "Used strictly as a ranking signal per design rule #2."
        ),
    )


class MatchResponse(BaseModel):
    matches: list[MatchResultItem] = Field(
        ...,
        description="List of internship matches, sorted in descending order of cosine similarity score",
    )
    sorted: bool = Field(
        True,
        description="True indicating results are sorted descending by similarity_score (highest first)",
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health")
def health():
    return {"service": "ai-service", "status": "ok"}


@app.post("/extract-resume")
async def extract_resume(file: UploadFile = File(...)):
    """
    Accept a PDF resume and return structured profile section text.

    This extraction is a first-pass heuristic — accuracy varies by resume
    format. See app/extractor.py for full accuracy caveats.

    TODO(measure after real evaluation): track precision/recall of section
    detection against a labelled resume corpus before relying on these
    outputs downstream.

    Returns:
        JSON object with nullable string fields:
          skills, education, experience, projects, certifications, interests.
        Additional '_note' key when no text layer is found (scanned PDF).

    Raises:
        400 if the uploaded file is not a PDF.
        422 if the PDF cannot be parsed at all (corrupt / encrypted).
    """
    # Validate type
    if file.content_type not in _ACCEPTED_PDF_TYPES:
        raise HTTPException(
            status_code=400,
            detail=f"Only PDF files are accepted. Received content-type: {file.content_type}",
        )
    filename = file.filename or ""
    if not filename.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=400,
            detail="File must have a .pdf extension.",
        )

    content = await file.read()
    if not content:
        raise HTTPException(status_code=422, detail="Uploaded file is empty.")

    # Extract text — raises ValueError for malformed PDFs
    try:
        text = extract_text_from_pdf(content)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    # Scanned/image-only PDFs have no text layer; pdfminer returns empty string.
    # OCR is not supported in this version.
    if not text.strip():
        return {
            "skills": None,
            "education": None,
            "experience": None,
            "projects": None,
            "certifications": None,
            "interests": None,
            "_note": (
                "No extractable text found. The PDF may be a scanned image. "
                "OCR is not supported in this version."
            ),
        }

    sections = parse_sections(text)
    return sections


@app.post("/embed", response_model=EmbedResponse)
def embed_endpoint(req: EmbedRequest):
    """
    Encode text and return a 384-dimensional Sentence-BERT vector.

    Uses all-MiniLM-L6-v2 to produce L2-normalized dense embeddings.
    """
    cleaned = req.text.strip()
    if not cleaned:
        raise HTTPException(status_code=422, detail="Input text cannot be empty or blank.")

    vector = compute_embedding(cleaned)
    return EmbedResponse(embedding=vector, dimensions=len(vector))


@app.post("/match", response_model=MatchResponse)
def match_endpoint(req: MatchRequest):
    """
    Compute cosine similarity scores for a resume against a list of internships.

    Compliance:
      - Design Rule #1: Pure similarity service — no mandatory filtering or
        business logic here. All structured filters run in Spring Boot before
        semantic matching.
      - Design Rule #2: Raw cosine similarity scores returned as ranking signals.
        Never framed as percentage match or probability.

    Ordering:
      - Results are returned SORTED in descending order of similarity_score
        (highest similarity first).
    """
    internship_dicts = [item.model_dump() for item in req.internships]
    matches = compute_matches(req.resume, internship_dicts)
    return MatchResponse(matches=matches, sorted=True)
